name: Pack extension
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: linux
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm install -g vsce
      - name: Set helper variables
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/*/v}" | tee -a $GITHUB_ENV
      - name: Change version number
        run: |
          sed -r -i'' "s/\"0.0.1\"/\"${{ env.GITHUB_TAG }}\"/g" package.json
          cat package.json
      - name: Pack the extension
        run: vsce package
      - name: Extension to Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: hardwario-tower-${{ env.GITHUB_TAG }}.vsix
      - name: Release the extension to marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish
